blog:
  build: .
  ports:
    - "8800:80"
  volumes:
    - "./hexo/source:/DATA/source"
    - "./hexo/themes:/DATA/themes"
    - "./config/_config.yml:/DATA/_config.yml"
    - "./config/themes/next/_config.yml:/DATA/themes/next/_config.yml"
  environment:
    VIRTUAL_HOST: icyleaf.com
    LETENCRYPT_HOST: icyleaf.com
    LETENCRYPT_EMAIL: icyleaf.cn@gmail.com
  restart: always