version: '2'
services:
  data:
    image: icyleafcn/hugo
    command: ash /run.sh
    volumes:
      - ./system/data/run.sh:/run.sh
      - ./site:/site
    env_file:
      - .env
  web:
    image: icyleafcn/caddy
    volumes_from:
      - data
    volumes:
      - ./system/web/Caddyfile:/etc/Caddyfile
    environment:
      - HOST=${HOST}
      - HTTP_PORT=${HTTP_PORT}
    ports:
      - "${HTTP_PORT}:80"