version: '2'
services:
  data:
    image: icyleafcn/hugo
    command: ash /run.sh
    volumes:
      - .:/site
      - ./system/data/run.sh:/run.sh
    environment:
      - HUGO_VERSION=0.19
      - HOST=localhost
      - HTTP_PORT=2015
    ports:
      - "1313:${HTTP_PORT}"
  web:
    build: .
    image: icyleafcn/caddy:dev
    ports:
      - "${HTTP_PORT}:80"
