data:
  image: icyleafcn/hugo
  command: ash -c "mkdir -p logs && hugo"
  volumes:
    - /data/sites/icyleaf.com/site:/site
  labels:
    - "io.rancher.container.network=true"
web:
  image: icyleafcn/caddy
  restart: always
  volumes_from:
    - data
  volumes:
    - /data/sites/icyleaf.com/system/web/Caddyfile:/etc/Caddyfile
  environment:
    - VIRTUAL_HOST=icyleaf.com
    - LETSENCRYPT_HOST=icyleaf.com
    - LETSENCRYPT_EMAIL=icyleaf.cn@gmail.com
  labels:
    - "io.rancher.container.network=true"