version: '2'
services:
  data:
    image: icyleafcn/hugo
    command: ash /run.sh
    volumes:
      - .:/site
      - ./system/data/run.sh:/run.sh
    environment:
      - HUGO_VERSION="0.19"
    env_file:
      - .env
  web:
    build: .
    image: icyleafcn/caddy:dev
    volumes_from:
      - data
    ports:
      - "${HTTP_PORT}:80"
