version: '2'

services:
  blog:
    build: .
    ports:
      - "8800:80"
    volumes:
      - "./hexo/source:/DATA/source"
      - "./hexo/themes:/DATA/themes"
      - "./config/_config.yml:/DATA/_config.yml"
      - "./config/themes/next/_config.yml:/DATA/themes/next/_config.yml"
    restart: always