version: '2'
services:
  data:
    image: icyleafcn/hugo
    command: ash /run.sh
    volumes:
      - ./system/data/run.sh:/run.sh
      - ./site:/site
    envrioment:
      - HUGO_HOST=https://icyleaf.com
      - HUGO_PORT=80
  web:
    image: icyleafcn/caddy
    volumes_from:
      - data
    volumes:
      - ./system/web/Caddyfile:/etc/Caddyfile
    ports:
      - "80:80"