version: '2'

services:
  blog:
    build: .
    volumes:
      - "./hexo/source:/DATA/source"
      - "./hexo/themes:/DATA/themes"
      - "./config/_config.yml:/DATA/_config.yml"
      - "./config/themes/next/_config.yml:/DATA/themes/next/_config.yml"
    environment:
      - VIRTUAL_HOST="icyleaf.com,www.icyleaf.com"
      - LETENCRYPT_HOST="icyleaf.com,www.icyleaf.com"
      - LETENCRYPT_EMAIL="icyleaf.cn@gmail.com"
    restart: always
  nginx:
    image: jwilder/nginx-proxy
    volumes:
      - /data/certs:/etc/nginx/certs:ro
      - /etc/nginx/vhost.d
      - /usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    ports:
      - 80:80
      - 443:443
    restart: always
  letencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    volumes_from:
      - nginx
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: always