version: '2'
services:
  data:
    image: icyleafcn/hugo
    command: ash /run.sh
    volumes:
      - ./system/data/run.sh:/run.sh
      - ./site:/site
    envrioment:
      - HOST=icyleaf.com
      - HTTP_PORT=1313
  web:
    image: icyleafcn/caddy
    volumes_from:
      - data
    volumes:
      - ./system/web/Caddyfile:/etc/Caddyfile
    ports:
      - "1313:80"