name = "Casper"
license = "MIT"
licenselink = "https://github.com/vjeantet/hugo-theme-casper/blob/master/LICENSE.md"
description = "Casper theme from Ghost Foundation"
homepage = "http://icyleaf.com/"
tags = ["blog"]
features = ["disqus", "google analytics","share"]
min_version=0.15

[author]
  name = "icyleaf"
  homepage = "http://icyleaf.com/"

[original]
  name = "hugo-theme-casper"
  homepage = "https://github.com/vjeantet/hugo-theme-casper"
  repo = "https://github.com/vjeantet/hugo-theme-casper"
