data:
  image: icyleafcn/hugo
  command: ash /run.sh
  volumes:
    - /data/sites/icyleaf.com/site:/site
    - /data/sites/icyleaf.com/system/data/run.sh:/run.sh
  environment:
    - HUGO_HOST=https://icyleaf.com
    - HUGO_PORT=80
  labels:
    - "io.rancher.container.network=true"
web:
  image: icyleafcn/caddy
  restart: always
  volumes_from:
    - data
  volumes:
    - /data/sites/icyleaf.com/system/web/Caddyfile:/etc/Caddyfile
  environment:
    - VIRTUAL_HOST=icyleaf.com,www.icyleaf.com
    - LETSENCRYPT_HOST=icyleaf.com,www.icyleaf.com
    - LETSENCRYPT_EMAIL=icyleaf.cn@gmail.com
  labels:
    - "io.rancher.container.network=true"