---
label: default
hide_body: false
fields:
- name: title
  default: ''
  label: Title
  type: text
  hidden: false
- name: date
  default: '2016-07-19T12:12:07.000+00:00'
  label: Date
  type: datetime
  hidden: false
- name: slug
  default: ''
  label: Slug
  type: text
  hidden: false
- name: categories
  default:
  - Technology
  label: Categories
  type: list
  hidden: false
- name: tags
  default:
  - Book
  label: Tags
  type: list
  hidden: false
- name: image
  default: images/cover.jpg
  label: Image
  type: file
  hidden: false
- name: menu
  default: ''
  label: Menu
  type: text
  hidden: true
- name: index
  default: false
  label: Index
  type: boolean
  hidden: false
- name: draft
  default: false
  label: Draft
  type: boolean
  hidden: false
- name: comments
  default: true
  label: Comments
  type: boolean
  hidden: false
- name: share
  default: true
  label: Share
  type: boolean
  hidden: false
pages:
- content/post/2017-05-10-fast-crystal.md
